<?php
/*
 * Doctrine Admin
 * Copyright (C) 2013 Bastiaan Welmers, bastiaan@welmers.net
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

use Bast1aan\DoctrineAdmin\View\EntityList;
use Bast1aan\DoctrineAdmin\ScalarProperty;
use Bast1aan\DoctrineAdmin\AssociationProperty;
use Bast1aan\DoctrineAdmin\CollectionAssociationProperty;

if ($this instanceof EntityList) :
$view = $this->getView();
$collection = $this->getCollection();
$fieldNames = array_merge($collection->getFieldNames(), $collection->getAssociationNames());
?>
<table class="doctrine_admin_list">
	<thead>
	<tr>
<?php foreach($fieldNames as $header) : ?>
		<th><?php print $header ?></th>
<?php endforeach ?>
	</tr>
	</thead>
	<tbody>
<?php foreach($collection as $entity) : ?>
<tr>
<?php foreach($fieldNames as $name) :
	$property = $entity->getColumn($name);
	if ($property instanceof ScalarProperty):
	$propertyStr = $view->formatScalarPropertyToString($property);
	if ($property->isId()): ?>
		<td class="target_entity <?php print str_replace('\\', '-', get_class($entity->getOriginalEntity()));?>">
		<span class="target_entity_id <?php print urlencode($view->renderEntityId($entity)) ?>"><?php print $propertyStr ?></span>
		</td>
<?php else: ?><td><?php print $propertyStr ?></td><?php endif;
elseif ($property instanceof CollectionAssociationProperty):?>
		<td class="target_entity <?php print str_replace('\\', '-', $property->getEntityName());?>">
			<ul>
<?php foreach($property as $targetEntity): ?>
					<li><span class="target_entity_id <?php print $view->renderEntityId($targetEntity) ?>"><?php print $view->renderEntity($targetEntity) ?></span></li>
<?php endforeach ?>
			</ul>
		</td>
<?php elseif ($property instanceof AssociationProperty): $targetEntity = $property->getValue(); ?>
<td class="target_entity <?php print str_replace('\\', '-', $property->getEntityName());?>">
<?php if($targetEntity != null): ?><span class="target_entity_id <?php print $view->renderEntityId($targetEntity) ?>"><?php print $view->renderEntity($targetEntity) ?></span><?php endif ?>
</td>
<?php endif ?>
<?php endforeach ?>
</tr>
<?php endforeach ?>
</tbody>
</table>
<?php endif ?>