 <?php
/*
 * Doctrine Admin
 * Copyright (C) 2013 Bastiaan Welmers, bastiaan@welmers.net
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

if ($this instanceof \Bast1aan\DoctrineAdmin\View\FormElementAssociation):
$entity = $this->property->getValue();
$isReadOnly = $this->property->isReadOnly();
if ($this->property->isNull()):
?>
	<input <?php if($isReadOnly):?>readonly="readonly" <?php endif ?>class="doctrine_admin_form_element_association" type="text" name="<?php print $this->property->getName() ?>" />
<?php else: ?>
 <span class="target_entity_id <?php print $this->getView()->renderEntityId($entity) ?>"><?php print $this->getView()->renderEntity($entity) ?></span> <input <?php if($isReadOnly):?>readonly="readonly" <?php endif ?> class="doctrine_admin_form_element_association" type="text" name="<?php print $this->property->getName() ?>" value="<?php print $this->getView()->renderEntityId($entity) ?>" />
<?php endif ?>
<?php endif ?>