<?php
/*
 * Doctrine Admin
 * Copyright (C) 2013 Bastiaan Welmers, bastiaan@welmers.net
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

use Bast1aan\DoctrineAdmin\View\Form;
use Bast1aan\DoctrineAdmin\AssociationProperty;

if ($this instanceof Form) :

$entity = $this->getEntity();

?>
<table class="doctrine_admin_form">
	<thead>
		<tr><th>Field</th><th>Null</th><th>Contents</th></th></tr>
	</thead>
	<tbody>
<?php foreach(array_merge($entity->getFieldNames(), $entity->getAssociationNames()) as $fieldName):
$element = $this->getElement($fieldName);
$property = $element->getProperty();

$trClass = '';
if ($property instanceof AssociationProperty) {
	$trClass = ' class="target_entity ' . str_replace('\\', '-', $property->getEntityName()) . '"';
}
?>
	<tr<?php print $trClass ?>><th><?php echo $fieldName ?></th><td><?php if ($property->isNullable()): ?><input type="checkbox" name="<?php print Form::FIELD_NAME_IS_NULL ?>[<?php print $fieldName ?>]" value="true" <?php if ($property->isNull()):?>checked="checked" <?php endif ?>/><?php endif ?></td><td><?php echo $element ?></td></tr>
<?php endforeach ?>
	</tbody>
</table>
<?php endif ?>